app = 'shopping-lists-without-any-geese-bot'
primary_region = 'bom'

[build]
dockerfile = 'Dockerfile'
image_tag = "latest"

[env]
RUST_LOG = 'info'
DB_URL = 'sqlite:///data/shopping.db'

[[mounts]]
source = 'shopbot_db'
destination = '/data'

# [[services]]
# protocol = 'tcp'
# internal_port = 8080
#
# [[services.ports]]
# port = 443
#
# [[services.ports]]
# port = 80
# handlers = ['http_redirect']
#
[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
